export const DRIVER_PHOTO_MAP: Record<string, string | null> = {
  VER: "ver.png",
  NOR: "nor.png",
  LEC: "lec.png",
  HAM: "ham.png",
  PIA: "pia.png",
  RUS: "rus.png",
  ANT: "ant.png",
  SAI: "sai.png",
  ALO: "alo.png",
  STR: "str.png",
  GAS: "gas.png",
  DOO: "doo.png",
  TSU: "tsu.png",
  HAD: "had.png",
  HUL: "hul.png",
  BOR: "bor.png",
  ALB: "alb.png",
  PER: "per.png",
  BEA: "bea.png",
  OCO: "oco.png",
  COL: "col.png",
  LAW: "law.png",
  BOT: "bot.png",
  LIN: "lin.png",
};
